// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCbOecRNx3BxzfBfQrC_9GF0l6IYkD9sfs",
    authDomain: "hospiconnect-f206f.firebaseapp.com",
    projectId: "hospiconnect-f206f",
    storageBucket: "hospiconnect-f206f.firebasestorage.app",
    messagingSenderId: "503637092506",
    appId: "1:503637092506:web:42382ca07c9379c3701723",
    measurementId: "G-J91NPZVR7S",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx0J5uG8YGJxJP_vV__jgo0EsSNQ5U9tE',
    appId: '1:503637092506:android:97bb7dda030f9e4f701723',
    messagingSenderId: '503637092506',
    projectId: 'hospiconnect-f206f',
    storageBucket: 'hospiconnect-f206f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.ambulanceApp',
  );
}
